project:
  type: website
  output-dir: _site

website:
  title: "Config Validator Service"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: pipeline.qmd
        text: Jenkins Pipeline
      - href: environment.qmd
        text: Docker Environment

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2